server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://192.168.1.241:3306/administration-microservice
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  http:
    encoding:
      charset: UTF-8
      force: true
  messages:
    encoding: UTF-8  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    service-url.defaultZone: http://192.168.1.241:8761/eureka/
  instance:
    hostname: 192.168.1.241
    lease-renewal-interval-in-seconds: 30
user:
  microservice:
    url: http://192.168.1.241:8002/api/v1/users
auth:
  microservice:
    url: http://192.168.1.241:8001/api/v1
