server:
  port: 8021
tomcat: 
  relaxed-query-chars: ['{','}']  
spring:
  datasource:
    url: jdbc:mysql://192.168.1.241:3306/cartera-temporal
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  http:
    encoding:
      charset: UTF-8
      force: true
  messages:
    encoding: UTF-8  
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true  
    service-url.defaultZone: http://192.168.1.241:8761/eureka/
  instance:
    hostname: 192.168.1.241
    lease-renewal-interval-in-seconds: 30
user:
  microservice:
    url: http://192.168.1.171:8002/api/v1/users
clientes:
  temporal: http://192.168.1.28:8020/api/v1/clientes
auth:
  microservice:
    url: http://192.168.1.171:8001/api/v1  