server:
  port: 8012
spring:
  task:
    executor:
      pool:
        core-size: 10
        max-size: 50
      queue-capacity: 100
  datasource:
    url: jdbc:mysql://192.168.1.241:3306/creditos-microservice
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
  cache:
    type: redis
  redis:
    host: redis-server
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,logfile
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url.defaultZone: http://192.168.1.241:8761/eureka/
  instance:
    hostname: 192.168.1.241
    lease-renewal-interval-in-seconds: 30

user:
  microservice:
    url: http://192.168.1.171:8002/api/v1/users
auth:
  microservice:
    url: http://192.168.1.171:8001/api/v1

administration:
  microservice:
    url: http://192.168.1.241:8003/api/v1/roles
clientes:
  microservice:
    url: http://192.168.1.241:8004/api/v1
jwt:
  secret: electrohogar

url-back: http://192.168.1.241:8012/api/v1
url: /data/uploads/
